Debugged format tester

diff --git a/tests/run_test_format.in b/tests/run_test_format.in
--- a/tests/run_test_format.in
+++ b/tests/run_test_format.in
@@ -1,48 +1,51 @@
 #!/bin/sh
 
 my_name=`basename "${0}"`
-my_fmt=`cut -d_ -f4`
-refdir="@srcdir@/psp_references"
+my_fmt=`echo "${my_name}" | cut -d_ -f4`
+psp_root="@srcdir@/../psp_references"
 
 if test "${my_fmt}" = ""; then
-  echo "This program is intended to be run by the test suite of Pspio" >&2
-  exit 1
+  echo "${my_name}: must be run by the test suite of Pspio" >&2
+  exit 101
 fi
-
-echo "Selecting format"
 
 case "${my_fmt}" in
   1|2|3|4|5|6|7|8|9|10|11|12)
-    pspdir="abinit${my_fmt}"
+    psp_dir="abinit${my_fmt}"
     ;;
   13)
-    pspdir="atom"
+    psp_dir="atom"
     ;;
   14)
-    pspdir="fhi"
+    psp_dir="fhi"
     ;;
   15)
-    pspdir="octopus_hgh"
+    psp_dir="octopus_hgh"
     ;;
   16)
-    pspdir="siesta"
+    psp_dir="siesta"
     ;;
   17)
-    pspdir="UPF"
+    psp_dir="UPF"
     ;;
   *)
-    echo "Unknown pseudopotential format" >&2
-    exit 2
+    echo "${my_name}: unknown pseudopotential format" >&2
+    exit 102
     ;;
 esac
 
-echo "will look for pseudos in ${refdir}/${pspdir}"
-set -v
+if test ! -d "${psp_root}/${psp_dir}"; then
+  echo "${my_name}: missing pseudopotential directory '${psp_dir}'" >&2
+  exit 103
+fi
 
-for pspfile in ${refdir}/${pspdir}/*; do
-  if test "${pspfile}" != "README"; then
-    ./test_format "${my_fmt}" "${pspfile}"
+ret=0
+for psp_file in ${psp_root}/${psp_dir}/*; do
+  if test "`basename ${psp_file}`" != "README"; then
+    ./test_format "${my_fmt}" "${psp_file}"
+    ret="${?}"
+    test "${ret}" = "0" || break
   fi
 done
 
-exit 0
+exit "${ret}"
